gdlearn:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

#  当期pickup角色的数据库id
#  gacha:
#    pickup5starid: 1
#    pickup4starid1: 3
#    pickup5starid2: 9
#    pickup5starid3: 11
